/**
 * HCL Project KEEP Core API v1
 * REST APIs for Domino and more done right. With declarative security and access to Code, Design and data
 *
 * The version of the OpenAPI document: 4.3.9
 * Contact: HeyHCL@pnp-hcl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openntf.xsp.nosql.communication.driver.keep.client.model;

import jakarta.json.bind.annotation.JsonbProperty;

/**
  * Definition of a Keep configuration.
 **/

public class AdminBackup  {
  
 /**
   * Basic information about Keep. 
  **/
  @JsonbProperty("version")
  private Object version;

 /**
   * All database configuration, including keepconfig(KeepConfig.nsf) which has configuration settings for the KEEP API. 
  **/
  @JsonbProperty("databases")
  private Object databases;

 /**
   * Application configuration. 
  **/
  @JsonbProperty("apps")
  private Object apps;

 /**
   * Basic information about Keep. 
   * @return version
  **/
  public Object getVersion() {
    return version;
  }

  /**
    * Set version
  **/
  public void setVersion(Object version) {
    this.version = version;
  }

  public AdminBackup version(Object version) {
    this.version = version;
    return this;
  }

 /**
   * All database configuration, including keepconfig(KeepConfig.nsf) which has configuration settings for the KEEP API. 
   * @return databases
  **/
  public Object getDatabases() {
    return databases;
  }

  /**
    * Set databases
  **/
  public void setDatabases(Object databases) {
    this.databases = databases;
  }

  public AdminBackup databases(Object databases) {
    this.databases = databases;
    return this;
  }

 /**
   * Application configuration. 
   * @return apps
  **/
  public Object getApps() {
    return apps;
  }

  /**
    * Set apps
  **/
  public void setApps(Object apps) {
    this.apps = apps;
  }

  public AdminBackup apps(Object apps) {
    this.apps = apps;
    return this;
  }


  /**
    * Create a string representation of this pojo.
  **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminBackup {\n");
    
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    databases: ").append(toIndentedString(databases)).append("\n");
    sb.append("    apps: ").append(toIndentedString(apps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

