/**
 * HCL Project KEEP Core API v1
 * REST APIs for Domino and more done right. With declarative security and access to Code, Design and data
 *
 * The version of the OpenAPI document: 4.3.9
 * Contact: HeyHCL@pnp-hcl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openntf.xsp.nosql.communication.driver.keep.client.model;

import jakarta.json.bind.annotation.JsonbProperty;
import jakarta.validation.constraints.NotNull;

/**
  * Response for a client_secret request. Client seccret is returned once
 **/

public class OAuthApplicationSecretResponse  {
  
 /**
   * application ID, required as header for access
  **/
  @JsonbProperty("client_id")
  private String clientId;

 /**
   * The application secret generated by Keep for the external application
  **/
  @JsonbProperty("client_secret")
  private String clientSecret;

 /**
   * The application secret generated by Keep for the external application
  **/
  @JsonbProperty("appSecret")
  private String appSecret;

 /**
   * application ID, required as header for access
   * @return clientId
  **/
  @NotNull
  public String getClientId() {
    return clientId;
  }

  /**
    * Set clientId
  **/
  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public OAuthApplicationSecretResponse clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

 /**
   * The application secret generated by Keep for the external application
   * @return clientSecret
  **/
  @NotNull
  public String getClientSecret() {
    return clientSecret;
  }

  /**
    * Set clientSecret
  **/
  public void setClientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
  }

  public OAuthApplicationSecretResponse clientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
    return this;
  }

 /**
   * The application secret generated by Keep for the external application
   * @return appSecret
  **/
  public String getAppSecret() {
    return appSecret;
  }

  /**
    * Set appSecret
  **/
  public void setAppSecret(String appSecret) {
    this.appSecret = appSecret;
  }

  public OAuthApplicationSecretResponse appSecret(String appSecret) {
    this.appSecret = appSecret;
    return this;
  }


  /**
    * Create a string representation of this pojo.
  **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OAuthApplicationSecretResponse {\n");
    
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    clientSecret: ").append(toIndentedString(clientSecret)).append("\n");
    sb.append("    appSecret: ").append(toIndentedString(appSecret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

