/**
 * HCL Domino REST API basis
 * REST APIs for Domino and more done right. With declarative security and access to Code, Design and Data
 *
 * The version of the OpenAPI document: 1.0.10
 * Contact: HeyHCL@pnp-hcl.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openntf.xsp.nosql.communication.driver.keep.client.model;

import java.util.List;

import jakarta.json.bind.annotation.JsonbProperty;

/**
  * Details of the current User Entry for a specific Database.
 **/

public class ScopeAccessUserEntry  {
  
 /**
   * Current user logged in
  **/
  @JsonbProperty("User")
  private String user;

 /**
   * ACL Level of the current logged in user
  **/
  @JsonbProperty("Level")
  private String level;

 /**
   * All of the roles of the current user logged in on the Domino REST API database
  **/
  @JsonbProperty("Roles")
  private List<String> roles = null;

 /**
   * Specifies what the current user are capable of doing on the Domino REST API database
  **/
  @JsonbProperty("Flags")
  private List<String> flags = null;

 /**
   * Current user logged in
   * @return user
  **/
  public String getUser() {
    return user;
  }

  /**
    * Set user
  **/
  public void setUser(String user) {
    this.user = user;
  }

  public ScopeAccessUserEntry user(String user) {
    this.user = user;
    return this;
  }

 /**
   * ACL Level of the current logged in user
   * @return level
  **/
  public String getLevel() {
    return level;
  }

  /**
    * Set level
  **/
  public void setLevel(String level) {
    this.level = level;
  }

  public ScopeAccessUserEntry level(String level) {
    this.level = level;
    return this;
  }

 /**
   * All of the roles of the current user logged in on the Domino REST API database
   * @return roles
  **/
  public List<String> getRoles() {
    return roles;
  }

  /**
    * Set roles
  **/
  public void setRoles(List<String> roles) {
    this.roles = roles;
  }

  public ScopeAccessUserEntry roles(List<String> roles) {
    this.roles = roles;
    return this;
  }

  public ScopeAccessUserEntry addRolesItem(String rolesItem) {
    this.roles.add(rolesItem);
    return this;
  }

 /**
   * Specifies what the current user are capable of doing on the Domino REST API database
   * @return flags
  **/
  public List<String> getFlags() {
    return flags;
  }

  /**
    * Set flags
  **/
  public void setFlags(List<String> flags) {
    this.flags = flags;
  }

  public ScopeAccessUserEntry flags(List<String> flags) {
    this.flags = flags;
    return this;
  }

  public ScopeAccessUserEntry addFlagsItem(String flagsItem) {
    this.flags.add(flagsItem);
    return this;
  }


  /**
    * Create a string representation of this pojo.
  **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScopeAccessUserEntry {\n");
    
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    roles: ").append(toIndentedString(roles)).append("\n");
    sb.append("    flags: ").append(toIndentedString(flags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

